---
# tasks file for ansible-prometheus-tools
#######Install node-exporter############
  - name: create user
    block:
      - name: Add user nologin for node_exporter
        user:
          name: node_exporter
          shell: /usr/bin/false
#Copy file for install

      - name: Copy file with owner and permissions
        copy:
          src: node_exporter-1.8.2.darwin-amd64.tar.gz
          dest: ~
      - name: Check system information
        shell:
            "tar -xvzf ~/node_exporter-1.8.2.darwin-amd64.tar.gz"



            #####Iam working on it right NOW###
